// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jldgwuguixnryfrvsuaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsZGd3dWd1aXhucnlmcnZzdWF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMzIzMzEsImV4cCI6MjA1OTcwODMzMX0.1x6sXaHEIHgBYFKzPOASpKnMPs4I7SjSlkHfpfvtiQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);